export const data = [
  {
    id: 75,
    title: "Nova oportunidade 002",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-02-22T16:21:37.921Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-02-22T16:21:37.921Z",
    valor_total_final: null,
    data_de_fechamento: "2023-02-23T03:00:00.000Z",
    quantidade: "10",
    celular_pessoal: "",
    cpf_cliente: "",
    cnpj_cliente: "",
    celular_2: "",
  },
  {
    id: 74,
    title: "Nova oportunidade 001",
    stageId: 2,
    stageName: "Proposta",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-02-17T17:34:54.732Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-02-17T17:35:30.527Z",
    valor_total_final: null,
    data_de_fechamento: "2023-02-22T03:00:00.000Z",
    quantidade: "1",
    celular_pessoal: "",
    cpf_cliente: "",
    cnpj_cliente: "",
    celular_2: "",
  },
  {
    id: 73,
    title: "teste novo",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 78,
    accountName: "teste novo",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T14:12:57.118Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T14:12:57.118Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 72,
    title: "1901Teste10",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 60,
    accountName: "Teste Raniel 001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T14:11:31.197Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T14:11:31.197Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 71,
    title: "1901Teste09",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 77,
    accountName: "1901Teste05",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T14:06:11.340Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T14:06:11.340Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 70,
    title: "1901Teste08",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 77,
    accountName: "1901Teste05",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T14:04:26.820Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T14:04:26.820Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 69,
    title: "1901Teste07",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 77,
    accountName: "1901Teste05",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T12:18:37.657Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T12:18:37.657Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 68,
    title: "1901Teste05",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 77,
    accountName: "1901Teste05",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T12:13:12.902Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T12:13:12.902Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 67,
    title: "1901Teste04",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 76,
    accountName: "1901Teste04",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T12:09:03.065Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T12:09:03.065Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 66,
    title: "1901Teste03",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 74,
    accountName: "1901Teste03",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T12:04:31.466Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T12:04:31.466Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 65,
    title: "1901Teste02",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 73,
    accountName: "1901Teste01",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T12:01:40.117Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T12:01:40.117Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 64,
    title: "1901Teste01",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 73,
    accountName: "1901Teste01",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-19T12:00:33.967Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-19T12:00:33.967Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 63,
    title: "TC002",
    stageId: 5,
    stageName: "Fechado Ganho",
    accountId: 34,
    accountName: "aaa",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T20:39:05.181Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T20:39:07.086Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 62,
    title: "TC001",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 34,
    accountName: "aaa",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T20:36:42.717Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T20:36:42.717Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 61,
    title: "TesteConversao1010",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 69,
    accountName: "TesteConversao001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T20:03:20.607Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T20:03:20.607Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 60,
    title: "teste pos mudanca de tabela",
    stageId: 5,
    stageName: "Fechado Ganho",
    accountId: 69,
    accountName: "TesteConversao001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T19:53:11.100Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T19:53:19.557Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 59,
    title: "TesteTeste",
    stageId: 5,
    stageName: "Fechado Ganho",
    accountId: 69,
    accountName: "TesteConversao001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T18:36:18.225Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T18:36:25.785Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 58,
    title: "TesteConversao005",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 72,
    accountName: "TesteConversao005",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T18:30:37.810Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T18:30:37.810Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 57,
    title: "TesteConversao004",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 39,
    accountName: "Conta 001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T18:28:55.554Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T18:28:55.554Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 56,
    title: "TesteConversao003",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 71,
    accountName: "TesteConversao003",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T18:27:18.599Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T18:27:18.599Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 55,
    title: "TesteConversao002",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 70,
    accountName: "TesteConversao002",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T18:08:17.455Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T18:08:17.455Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 54,
    title: "TesteConversao001",
    stageId: 1,
    stageName: "Fechado Perdido",
    accountId: 69,
    accountName: "TesteConversao001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T18:05:32.640Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T18:05:32.640Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 53,
    title: "Teste001",
    stageId: 1,
    stageName: "Negociação",
    accountId: 68,
    accountName: "Teste001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-18T17:59:23.283Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-18T17:59:23.283Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 52,
    title: "Teste Conversão 003",
    stageId: 1,
    stageName: "Negociação",
    accountId: 67,
    accountName: "Teste Conversão 003",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-17T12:35:50.658Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-17T12:35:50.658Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 51,
    title: "Teste Conversão 002",
    stageId: 1,
    stageName: "Negociação",
    accountId: 66,
    accountName: "Teste Conversão 002",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-17T12:34:07.613Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-17T12:34:07.613Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 50,
    title: "Teste Conversão 001",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 65,
    accountName: "Teste Conversão 001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-17T12:31:30.245Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-17T12:31:30.245Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 49,
    title: "Teste 002",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 64,
    accountName: "Novo conta teste 002",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-13T13:19:59.977Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-13T13:19:59.977Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 48,
    title: "Oportunidade 001",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 63,
    accountName: "Conta nova Lead 001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-13T13:04:49.948Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-13T13:04:49.948Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 47,
    title: "Teste Raniel 004",
    stageId: 5,
    stageName: "Fechado Ganho",
    accountId: 62,
    accountName: "Teste Raniel 004",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-04T19:59:17.159Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-05T21:07:43.379Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 46,
    title: "Teste Oportunidade 003",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 61,
    accountName: "Teste 002",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-04T19:56:12.726Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-04T19:56:12.726Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 45,
    title: "Teste Oportunidade 002",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 60,
    accountName: "Teste Raniel 001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-04T19:55:10.201Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-04T19:55:10.201Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 44,
    title: "Teste Raniel 001",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 60,
    accountName: "Teste Raniel 001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2023-01-04T19:26:00.086Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2023-01-04T19:26:00.086Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 43,
    title: "Teste nova oportunidade",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 51,
    accountName: "conta teste",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-12-20T20:47:56.474Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-12-20T20:47:56.474Z",
    valor_total_final: "12564",
    data_de_fechamento: "2022-12-23T03:00:00.000Z",
    quantidade: "56",
    celular_pessoal: "88998709558",
    cpf_cliente: "",
    cnpj_cliente: "21212121221212",
    celular_2: null,
  },
  {
    id: 42,
    title: "Teste app novos campos",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-12-20T13:47:11.340Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-12-20T13:51:46.771Z",
    valor_total_final: null,
    data_de_fechamento: "2022-12-23T03:00:00.000Z",
    quantidade: "1345",
    celular_pessoal: "88979797979",
    cpf_cliente: "",
    cnpj_cliente: "11111111111111",
    celular_2: null,
  },
  {
    id: 40,
    title: "Teste atualização",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 50,
    accountName: "Conta 001",
    recordTypeId: 303,
    createdByLogin: "elieudo.maia",
    createdByName: "Elieudo Maia",
    responsibleId: "elieudo.maia",
    responsibleName: "Elieudo Maia",
    createdAt: "2022-12-16T18:08:52.442Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-12-16T18:30:47.825Z",
    valor_total_final: "3000",
    data_de_fechamento: "2022-12-14T03:00:00.000Z",
    quantidade: "16",
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 39,
    title: "opp 77",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 50,
    accountName: "Conta 001",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-12-15T19:40:54.866Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-12-15T19:40:54.866Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 38,
    title: "teste criação 2",
    stageId: 2,
    stageName: "Proposta",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-11-17T21:27:51.769Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-11-24T17:50:35.114Z",
    valor_total_final: null,
    data_de_fechamento: "2022-12-10T03:00:00.000Z",
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 37,
    title: "teste criação 2",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-11-17T21:24:56.487Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-11-17T21:24:56.487Z",
    valor_total_final: null,
    data_de_fechamento: "2022-12-10T03:00:00.000Z",
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 36,
    title: "teste criação",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "elieudo.maia",
    responsibleName: "Elieudo Maia",
    createdAt: "2022-11-17T20:06:52.496Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-11-17T21:14:58.371Z",
    valor_total_final: null,
    data_de_fechamento: "2022-12-10T03:00:00.000Z",
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 35,
    title: "001 TESTE CORREÇÃO",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 49,
    accountName: "Conta conversão",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-11-17T19:12:02.091Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-11-17T19:12:02.091Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 27,
    title: "teste criação",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "elieudo.maia",
    responsibleName: "Elieudo Maia",
    createdAt: "2022-11-07T13:54:37.429Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-11-07T21:24:25.090Z",
    valor_total_final: null,
    data_de_fechamento: "2022-12-10T03:00:00.000Z",
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 26,
    title: "teste criação",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "elieudo.maia",
    responsibleName: "Elieudo Maia",
    createdAt: "2022-11-07T13:53:06.900Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-11-07T21:24:37.314Z",
    valor_total_final: null,
    data_de_fechamento: "2022-12-10T03:00:00.000Z",
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 25,
    title: "teste criação",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-11-07T13:50:43.049Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-11-07T13:50:43.049Z",
    valor_total_final: null,
    data_de_fechamento: "2022-12-10T03:00:00.000Z",
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 24,
    title: "Nov opp",
    stageId: 2,
    stageName: "Proposta",
    accountId: 37,
    accountName: "teste 2",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-26T10:50:39.270Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-31T20:45:35.344Z",
    valor_total_final: "0",
    data_de_fechamento: "2022-09-01T03:00:00.000Z",
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 23,
    title: "Oportunidade",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 36,
    accountName: "Teste",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-25T14:08:40.799Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-25T14:08:40.799Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 20,
    title: "12",
    stageId: 4,
    stageName: "Fechado Perdido",
    accountId: 35,
    accountName: "12",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-20T11:47:40.067Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-20T11:47:42.331Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 19,
    title: "Opp teste",
    stageId: 1,
    stageName: "Qualificação",
    accountId: null,
    accountName: null,
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-18T14:45:44.368Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-18T14:47:08.416Z",
    valor_total_final: "3000",
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 18,
    title: "novo lead 5",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 31,
    accountName: "novo lead 5",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-17T13:23:28.633Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T13:23:28.633Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 17,
    title: "novo lead 4",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 30,
    accountName: "novo lead 4",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-17T13:21:35.252Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T13:21:35.252Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 16,
    title: "novolead3",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 29,
    accountName: "novo lead3",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-17T13:19:05.741Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T13:19:05.741Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 15,
    title: "novo lead3",
    stageId: 5,
    stageName: "Fechado Ganho",
    accountId: 28,
    accountName: "novo lead3",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-17T13:08:56.933Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T13:18:43.798Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 14,
    title: "Novo lead2",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 27,
    accountName: "Novo lead2 ",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-17T13:03:00.112Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T13:03:00.112Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 13,
    title: "conversão",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 26,
    accountName: "conta conversão",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-17T12:50:09.953Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T12:50:09.953Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 12,
    title: "opp conversao",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 25,
    accountName: "Novo leconversaad",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-17T12:11:24.660Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T12:11:24.660Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 11,
    title: "Lead convertido 1",
    stageId: 4,
    stageName: "Fechado Perdido",
    accountId: 24,
    accountName: "Nova conta",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T23:27:16.590Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-17T12:09:11.022Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 10,
    title: "cascascasc",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 23,
    accountName: "123asd",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T23:08:09.537Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T23:08:09.537Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 9,
    title: "asascasccsdcsdcdsc",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 15,
    accountName: "Raniel - Pra converter",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T22:39:45.277Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T22:39:45.277Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 8,
    title: "asascasc",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 13,
    accountName: "Raniel - Pra converter",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T22:33:59.234Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T22:33:59.234Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 7,
    title: "cascascasc",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 11,
    accountName: "Raniel - Pra converter",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T22:32:34.811Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T22:32:34.811Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 6,
    title: "cascasc",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 1,
    accountName: "Conta Meu lead de teste",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T22:32:13.259Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T22:32:13.259Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 5,
    title: "para lead id 3",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 8,
    accountName: "conta lead id 3",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T22:04:58.671Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T22:04:58.671Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 4,
    title: "minha oportunidade",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 6,
    accountName: "Meu novo lead",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T22:00:33.368Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T22:00:33.368Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
  {
    id: 3,
    title: "Lead convertido 5",
    stageId: 1,
    stageName: "Qualificação",
    accountId: 4,
    accountName: "Conta 9",
    recordTypeId: 303,
    createdByLogin: "adm",
    createdByName: "adm",
    responsibleId: "adm",
    responsibleName: "adm",
    createdAt: "2022-10-14T21:55:48.828Z",
    lastUpdatedByLogin: "adm",
    lastUpdatedAt: "2022-10-14T21:55:48.828Z",
    valor_total_final: null,
    data_de_fechamento: null,
    quantidade: null,
    celular_pessoal: null,
    cpf_cliente: null,
    cnpj_cliente: null,
    celular_2: null,
  },
];
